In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('50-companies.csv')

In [3]:
dataset.head()

Major&Minor Works  R&D Spend  Marketing Spend   Location     Profit
0          185849.20  151897.80        492284.10  Bangalore  217261.83
1          183097.70  166377.59        464398.53  Hyderabad  216792.06
2          173941.51  116145.55        428434.54       Pune  216050.39
3          164872.41  133671.85        403699.62  Bangalore  207901.99
4          162607.34  106391.77        386668.42       Pune  191187.94

In [4]:
X = dataset.iloc[:, :-1].values
X

array([[185849.2, 151897.8, 492284.1, 'Bangalore'],
       [183097.7, 166377.59, 464398.53, 'Hyderabad'],
       [173941.51, 116145.55, 428434.54, 'Pune'],
       [164872.41, 133671.85, 403699.62, 'Bangalore'],
       [162607.34, 106391.77, 386668.42, 'Pune'],
       [152376.9, 114814.71, 383361.36, 'Bangalore'],
       [155115.46, 162198.87, 148216.82, 'Hyderabad'],
       [150798.13, 160530.06, 344376.68, 'Pune'],
       [141042.52, 163718.95, 332113.29, 'Bangalore'],
       [143834.88, 123679.17, 325481.62, 'Hyderabad'],
       [122413.08, 125594.11, 249660.95, 'Pune'],
       [121171.96, 106790.61, 270244.55, 'Hyderabad'],
       [114363.75, 142320.38, 270339.44, 'Pune'],
       [112492.39, 150495.07, 273164.93, 'Hyderabad'],
       [140443.24, 171547.42, 277012.92, 'Pune'],
       [135023.61, 137616.84, 282276.23, 'Bangalore'],
       [98513.11, 136597.55, 284846.06, 'Hyderabad'],
       [115157.16, 160077.58, 303074.31, 'Bangalore'],
       [112249.16, 129175.79, 315419.57, 'Pune

In [5]:
Y = dataset.iloc[:, 4].values
Y

array([217261.83, 216792.06, 216050.39, 207901.99, 191187.94, 181991.12,
       181122.51, 180752.6 , 177211.77, 174759.96, 171121.95, 169259.4 ,
       166585.52, 159307.35, 157602.65, 154917.04, 151992.93, 150370.37,
       149266.9 , 147776.86, 143474.03, 136313.02, 135352.25, 133733.99,
       133552.04, 132404.34, 130733.54, 130008.31, 128282.38, 126004.64,
       124937.59, 122483.56, 122427.84, 121778.92, 121712.8 , 121479.51,
       115708.19, 114949.14, 106229.06, 106005.76, 103239.91, 102798.83,
        96498.49,  94758.98,  90200.33,  89926.08,  74490.75,  67559.73,
        60673.41,  39681.4 ])

In [6]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 3] = labelencoder.fit_transform(X[:, 3])
onehotencoder = OneHotEncoder(categorical_features = [3])
X = onehotencoder.fit_transform(X).toarray()
print(X)

[[1.0000000e+00 0.0000000e+00 0.0000000e+00 1.8584920e+05 1.5189780e+05
  4.9228410e+05]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 1.8309770e+05 1.6637759e+05
  4.6439853e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 1.7394151e+05 1.1614555e+05
  4.2843454e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 1.6487241e+05 1.3367185e+05
  4.0369962e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 1.6260734e+05 1.0639177e+05
  3.8666842e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 1.5237690e+05 1.1481471e+05
  3.8336136e+05]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 1.5511546e+05 1.6219887e+05
  1.4821682e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 1.5079813e+05 1.6053006e+05
  3.4437668e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 1.4104252e+05 1.6371895e+05
  3.3211329e+05]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 1.4383488e+05 1.2367917e+05
  3.2548162e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 1.2241308e+05 1.2559411e+05
  2.4966095e+05]
 [0.0000000e+00 1.000

In [7]:
# Avoiding the Dummy Variable Trap
X = X[:, 1:]
print(X)

[[0.0000000e+00 0.0000000e+00 1.8584920e+05 1.5189780e+05 4.9228410e+05]
 [1.0000000e+00 0.0000000e+00 1.8309770e+05 1.6637759e+05 4.6439853e+05]
 [0.0000000e+00 1.0000000e+00 1.7394151e+05 1.1614555e+05 4.2843454e+05]
 [0.0000000e+00 0.0000000e+00 1.6487241e+05 1.3367185e+05 4.0369962e+05]
 [0.0000000e+00 1.0000000e+00 1.6260734e+05 1.0639177e+05 3.8666842e+05]
 [0.0000000e+00 0.0000000e+00 1.5237690e+05 1.1481471e+05 3.8336136e+05]
 [1.0000000e+00 0.0000000e+00 1.5511546e+05 1.6219887e+05 1.4821682e+05]
 [0.0000000e+00 1.0000000e+00 1.5079813e+05 1.6053006e+05 3.4437668e+05]
 [0.0000000e+00 0.0000000e+00 1.4104252e+05 1.6371895e+05 3.3211329e+05]
 [1.0000000e+00 0.0000000e+00 1.4383488e+05 1.2367917e+05 3.2548162e+05]
 [0.0000000e+00 1.0000000e+00 1.2241308e+05 1.2559411e+05 2.4966095e+05]
 [1.0000000e+00 0.0000000e+00 1.2117196e+05 1.0679061e+05 2.7024455e+05]
 [0.0000000e+00 1.0000000e+00 1.1436375e+05 1.4232038e+05 2.7033944e+05]
 [1.0000000e+00 0.0000000e+00 1.1249239e+05 1.50495

In [8]:
#splitting the dataset as training and testing dataset
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2, random_state=0)

In [9]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [10]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)